server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Disable auto routing
spring.cloud.gateway.discovery.locator.enabled=false

spring.cloud.gateway.default-filters[0]=PreserveHostHeader


# Product Service Route
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/products(?<segment>/?.*), /api/products${segment}
